web:
  url: http://192.168.100.114:8080
  casdoor-callback: ${web.url}/api/login/callback
casdoor:
  endpoint: https://oauth.xxxxxxxxxx.cn
  client-id: 54aba1exxxxxxxxxxxxx
  client-secret: 58a93442745950554ea2a980dxxxxxxxxxxxx
  organization-name: dev-org
  application-name: SimpleImgsPlatform
  certificate: "-----BEGIN CERTIFICATE-----\r\n
MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk\r\n
-----END CERTIFICATE-----"
server:
  port: 8081
  servlet:
    session:
      cookie:
        name: PHPSESSIONID
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.xxx.5:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
      username: xxxxxx
      password: xxxxxx
  session:
    store-type: redis
  redis:
    host: 192.168.xxxxx.5
    port: 6379
    database: 0
    password: xxxxxxxxxx
    jedis:
      pool:
        enabled: true
    client-type: jedis
  servlet:
    multipart:
      location: D:\\dev\\tmp\\
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bukkit.sip.orm.entity
  configuration:
    cache-enabled: true