spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bukkit.sip.orm.entity
  configuration:
    cache-enabled: true
  type-handlers-package: cn.bukkit.sip.orm.handler
web:
  url: http://192.168.100.114:8080
  casdoor-callback: ${web.url}/api/login/callback
  upload:
    allow-upload:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
      - svg
      - tiff