name: Build and Push The Docker Image
on:
  workflow_dispatch:
    inputs:
      tags:
        required: true
        description: 'Docker tags'
        type: string

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: zerek00/simple_assets_platform:${{ inputs.tags }},zerek00/simple_assets_platform:latest
