name: Pages Build
on:
  workflow_dispatch:
  push:
    branches: [ master-template ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15 ]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install and Build
        env:
          VUE_APP_ROUTER_BASE: /Simple-Assets-Platform/
        run: |
          pnpm install
          pnpm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
